apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pdf-api
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/YOUR_PROJECT_ID/pdf-api
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        resources:
          limits:
            memory: 2Gi
            cpu: "1"
        ports:
        - containerPort: 8080 